# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_auto_20161204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content'),
        ),
    ]
