# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0004_auto_20161204_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
